"""Spirrow-Prismind data models."""

from .catalog import CatalogEntry, SearchCatalogResult, SyncCatalogResult
from .document import (
    CreateDocumentResult,
    DeleteDocumentResult,
    DeleteDocumentTypeResult,
    DocReference,
    Document,
    DocumentResult,
    DocumentSummary,
    DocumentType,
    ListDocumentTypesResult,
    ListDocumentsResult,
    RegisterDocumentTypeResult,
    UpdateDocumentResult,
)
from .knowledge import (
    AddKnowledgeResult,
    KnowledgeEntry,
    SearchKnowledgeResult,
    UpdateKnowledgeResult,
)
from .progress import (
    GetProgressResult,
    PhaseProgress,
    PROGRESS_SHEET_HEADERS,
    TaskDefinition,
    TaskProgress,
    UpdateProgressResult,
    task_from_sheet_row,
    task_to_sheet_row,
)
from .project import (
    DeleteProjectResult,
    DocsConfig,
    DriveConfig,
    ListProjectsResult,
    ProjectConfig,
    ProjectOptions,
    ProjectSummary,
    SetupProjectResult,
    SheetsConfig,
    SimilarProject,
    SwitchProjectResult,
    SyncProjectsResult,
    UpdateProjectResult,
)
from .session import (
    DeleteSessionResult,
    EndSessionResult,
    ListSessionsResult,
    SaveSessionResult,
    SessionContext,
    SessionInfo,
    SessionState,
)
from .setup import (
    ConfigureResult,
    ExportServerConfigResult,
    GetConnectionInfoResult,
    GetSetupStatusResult,
    GoogleConnectionInfo,
    ImportServerConfigResult,
    ServiceConnectionInfo,
    SettingStatus,
)
from .summary import (
    CheckServicesResult,
    INITIAL_PROGRESS_DATA,
    ServiceStatus,
    SUMMARY_SHEET_TEMPLATE,
    UpdateSummaryResult,
    create_catalog_template,
    create_progress_template,
    create_summary_template,
)

__all__ = [
    # Catalog
    "CatalogEntry",
    "SearchCatalogResult",
    "SyncCatalogResult",
    # Document
    "CreateDocumentResult",
    "DeleteDocumentResult",
    "DeleteDocumentTypeResult",
    "DocReference",
    "Document",
    "DocumentResult",
    "DocumentSummary",
    "DocumentType",
    "ListDocumentTypesResult",
    "ListDocumentsResult",
    "RegisterDocumentTypeResult",
    "UpdateDocumentResult",
    # Knowledge
    "AddKnowledgeResult",
    "KnowledgeEntry",
    "SearchKnowledgeResult",
    "UpdateKnowledgeResult",
    # Progress
    "GetProgressResult",
    "PhaseProgress",
    "PROGRESS_SHEET_HEADERS",
    "TaskDefinition",
    "TaskProgress",
    "UpdateProgressResult",
    "task_from_sheet_row",
    "task_to_sheet_row",
    # Project
    "DeleteProjectResult",
    "DocsConfig",
    "DriveConfig",
    "ListProjectsResult",
    "ProjectConfig",
    "ProjectOptions",
    "ProjectSummary",
    "SetupProjectResult",
    "SheetsConfig",
    "SimilarProject",
    "SwitchProjectResult",
    "SyncProjectsResult",
    "UpdateProjectResult",
    # Session
    "EndSessionResult",
    "SaveSessionResult",
    "SessionContext",
    "SessionState",
    # Setup
    "ConfigureResult",
    "ExportServerConfigResult",
    "GetConnectionInfoResult",
    "GetSetupStatusResult",
    "GoogleConnectionInfo",
    "ImportServerConfigResult",
    "ServiceConnectionInfo",
    "SettingStatus",
    # Summary
    "CheckServicesResult",
    "INITIAL_PROGRESS_DATA",
    "ServiceStatus",
    "SUMMARY_SHEET_TEMPLATE",
    "UpdateSummaryResult",
    "create_catalog_template",
    "create_progress_template",
    "create_summary_template",
]
